[package]
name = "casile"
version = "0.10.9"
authors = [ "Caleb Maclennan <caleb@alerque.com>" ]
edition = "2018"
description = "The command line interface to the CaSILE toolkit, a book publishing workflow employing SILE and other wizardry"
homepage = "https://github.com/sile-typesetter/casile"
repository = "https://github.com/sile-typesetter/casile"
license = "AGPL-3"
build = "build.rs"

[dependencies]
colored = "2.0.0"
fluent = "0.12.0"
fluent-fallback = "0.0.4"
fluent-langneg = "0.13.0"
itertools = "0.10.3"
lazy_static = "1.4.0"
num_cpus = "1.15.0"
rayon = "1.6.1"
rust-embed = "6.4.2"
subprocess = "0.2.9"
unic-langid = "0.9.1"

  [dependencies.config]
  version = "0.13.2"
  default-features = false
  features = [ "yaml" ]

  [dependencies.clap]
  version = "3.2.20"
  features = [ "derive", "wrap_help" ]

  [dependencies.git2]
  version = "0.16.0"
  default-features = false

  [dependencies.git-warp-time]
  version = "0.4.9"
  default-features = false

  [dependencies.Inflector]
  version = "0.11.4"
  default-features = false

  [dependencies.regex]
  version = "1.7.1"
  default-features = false
  features = [ "std" ]

[build-dependencies]
clap = "3.2.20"
clap_complete = "3.2.4"

  [build-dependencies.vergen]
  version = "7.4.2"
  default-features = false
  features = [ "build", "git" ]

[dev-dependencies]
assert_cmd = "2.0.8"
predicates = "2.1.5"

[profile.release]
lto = true
