[package]
name = "casile"
version = "0.10.9"
authors = [ "Caleb Maclennan <caleb@alerque.com>" ]
edition = "2018"
description = "The command line interface to the CaSILE toolkit, a book publishing workflow employing SILE and other wizardry"
homepage = "https://github.com/sile-typesetter/casile"
repository = "https://github.com/sile-typesetter/casile"
license = "AGPL-3"
build = "build.rs"

[dependencies]
colored = "2.0"
fluent = "0.12"
fluent-fallback = "0.0"
fluent-langneg = "0.13"
itertools = "0.10"
lazy_static = "1.4"
num_cpus = "1.15"
rayon = "1.6"
rust-embed = "6.4"
subprocess = "0.2"
unic-langid = "0.9"

  [dependencies.config]
  version = "0.13"
  default-features = false
  features = [ "yaml" ]

  [dependencies.clap]
  version = "4.0"
  features = [ "derive", "wrap_help" ]

  [dependencies.git2]
  version = "0.16"
  default-features = false

  [dependencies.git-warp-time]
  version = "0.4"
  default-features = false

  [dependencies.Inflector]
  version = "0.11"
  default-features = false

  [dependencies.regex]
  version = "1.7"
  default-features = false
  features = [ "std" ]

[build-dependencies]

  [build-dependencies.clap]
  version = "4.0"
  features = [ "derive" ]

  [build-dependencies.clap_complete]
  version = "4.0"

  [build-dependencies.vergen]
  version = "7.4"
  default-features = false
  features = [ "build", "git" ]

[dev-dependencies]
assert_cmd = "2.0"
predicates = "2.1"

[profile.release]
lto = true
