name: Deploy

on:
  push:
    branches:
      - master
      - develop
      - rel*
    tags:
      - latest
      - v*

jobs:

  ghcr:
    strategy:
      fail-fast: false
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Configure
        run: |
          ./bootstrap.sh
          ./configure \
            --enable-developer-mode \
              DOCKER=$(which docker) \
            --without-developer-tools \
            --disable-dependency-checks
      - name: Publish Docker Image to GH Container Registry
        run: |
          make docker-build-push
        env:
          DOCKER_REGISTRY: ghcr.io
          DOCKER_REPO: ${{ github.repository }}
          DOCKER_TAG: ${{ github.ref_name }}
          DOCKER_USERNAME: ${{ github.actor }}
          DOCKER_PAT: ${{ secrets.CR_SILE_TYPESETTER }}
