name: Deploy

on:
  push:
    branches:
      - master
    tags:
      - latest
      - v*

jobs:

  ghcr:
    strategy:
      fail-fast: false
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Fetch tags
        run: |
          git fetch --prune --tags ||:
      - name: Setup system dependencies
        run: |
          sudo apt-get install autoconf-archive
      - name: Configure
        run: |
          ./bootstrap.sh
          ./configure \
            --without-{bash,fish,zsh}-completion-dir \
            --enable-developer \
            --disable-dependency-checks \
            DOCKER=docker DIFF=diff CURL=curl SORT=sort \
      - name: Publish Docker Image to GH Container Registry
        run: |
          make docker-build-push
        env:
          DOCKER_REGISTRY: ghcr.io
          DOCKER_REPO: ${{ github.repository }}
          DOCKER_TAG: ${{ github.ref_name }}
          DOCKER_USERNAME: ${{ github.actor }}
          DOCKER_PAT: ${{ secrets.CR_SILE_TYPESETTER }}
