name: Release

on:
  push:
    tags:
      - v*.*.*

jobs:

  ghrelase:
    strategy:
      fail-fast: false
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup system dependencies
        run: |
          sudo apt-get install autoconf-archive
      - name: Configure
        run: |
          echo "VERSION=${GITHUB_REF#refs/*/v}" >> $GITHUB_ENV
          echo "${GITHUB_REF#refs/*/v}" > .tarball-version
          ./bootstrap.sh
          ./configure \
            --enable-developer \
            --without-{bash,fish,zsh}-completion-dir \
            --disable-dependency-checks
      - name: Build source package
        run: |
          make dist
      - name: Publish Release
        uses: softprops/action-gh-release@v1
        if: github.repository == 'sile-typesetter/casile' && startsWith(github.ref, 'refs/tags/v')
        with:
          body_path: casile-${{ env.VERSION }}.md
          files: |
            casile-${{ env.VERSION }}.zip
            casile-${{ env.VERSION }}.tar.xz
